FORMAT: 1A
HOST: https://api.ritekit.com
# RiteKit API

RiteKit API is based on REST principles.

Authentication uses standard OAuth 2.0 process

##Getting started
1. Sign up for [RiteKit](https://ritekit.com/)
1. Go to [developer dashboard](https://ritekit.com/developer/dashboard/)
1. Click "Create a token" button to get your **Client ID** and **Client secret**
1. Study the documentation below (for more info on oAuth go to http://oauth.net/)
1. When you reach your free limit of calls per month, [upgrade to paid tiers](https://ritekit.com/developer/)

## Options for authorizing API Calls


#### A) Using Client ID directly

You can directly connect to our API using your **client ID** by sending it as a GET query parameter. This option is simple (no need for oAuth) but it should be used only in case the Client ID is not exposed publicly.

    GET  https://api.ritekit.com/v1/stats/basic/php?client_id=292c6912e7710c838347ae178b4a


#### B) Using Access token (oAuth 2.0)
Once you have valid Access token, you can access our API by sending the token in the Authorization header bearer or as a query Access token. See the oAuth 2.0 section to learn how to get Access token and keep refreshing it.

    Authorization: Bearer xxxx

Or

    GET  https://api.ritekit.com/v1/stats/basic/php?access_token=292c6912e7710c838347ae178b4a


## oAuth 2.0

![oauthschema](https://cdn.ritekit.com/assets/media/1/oauth-simple.png)

### Get Access Token

Use your Client Credentials to get the token.

    POST   https://ritekit.com/oauth/token

           grant_type=client_credentials
           &client_id=CLIENT_ID
           &client_secret=CLIENT_SECRET
           &scope=data

- [required] grant_type - client_credentials
- [required] client_id (CLIENT ID)
- [required] client_secret (CLIENT SECRET)
- [required] (always use scope=data)


#### Response

    {
        "access_token":292c6912e7710c838347ae178b4a,
        "token_type":"bearer",
        "expires_in": 3600,
        "refresh_token":292c6912e7710c838347ae178b4a,
    }


### Refresh token

Every Access token has a lifetime. You can use Refresh token to request a new Access Token.


    POST   https://ritekit.com/oauth/token

           grant_type=refresh_token
           &refresh_token=REFRESH_TOKEN
           &client_id=CLIENT_ID
           &scope=data

- [required] grant_type - refresh_token
- [required] refresh_token - (REFRESH TOKEN) the refresh token you got from the expired token
- [required] client_id (CLIENT ID)
- [required] client_secret (CLIENT SECRET)
- [required] scope (always use scope=data)


#### Response

    {
        "access_token":292c6912e7710c838347ae178b4a,
        "token_type":"bearer",
        "expires_in": 3600,
        "refresh_token":292c6912e7710c838347ae178b4a,
    }


## Hashtags [/v1/stats/]

### Auto-Hashtag [GET /v1/stats/auto-hashtag?post={post}]

Returns auto-hashtagged text of the post.

+ Parameters

    + post (string, `Is artificial intelligence the future of customer service?`) ... Text of the post

+ Request (text/html; charset=utf-8)

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "result": true,
                "code": 200,
                "message": "OK",
                "post": "Is artificial intelligence the #future of #CustomerService?"
            }


### Hashtag Suggestions [GET /v1/stats/hashtag-suggestions/{topic}]

Returns list of hashtag suggestions and their real-time stats for a given topic

+ Parameters

    + topic (string, `seo`) ... Topic

+ Request (text/html; charset=utf-8)

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "result": true,
                "code": 200,
                "message": "OK",
                "hashtag": "seo",
                "data": [
                    {
                        "hashtag": "seo",
                        "tag": "seo",
                        "tweets": 1383,
                        "exposure": 6463321,
                        "retweets": 750,
                        "images": 60.5929146,
                        "links": 93.420105,
                        "mentions": 6.3629789,
                        "color": 3,
                        "frequency": 9.986
                    },
                    {
                        "hashtag": "marketing",
                        "tag": "marketing",
                        "tweets": 1992,
                        "exposure": 17566846,
                        "retweets": 620,
                        "images": 39.5582314,
                        "links": 90.1606445,
                        "mentions": 19.026104,
                        "color": 3,
                        "frequency": 0.956
                    },
                    {
                        "hashtag": "google",
                        "tag": "google",
                        "tweets": 500,
                        "exposure": 1783683,
                        "retweets": 212,
                        "images": 51.5999985,
                        "links": 92.4000015,
                        "mentions": 8.3999996,
                        "color": 3,
                        "frequency": 0.908
                    },
                    {
                        "hashtag": "website",
                        "tag": "website",
                        "tweets": 333,
                        "exposure": 1750575,
                        "retweets": 67,
                        "images": 62.4624634,
                        "links": 96.3963928,
                        "mentions": 7.5075073,
                        "color": 3,
                        "frequency": 0.812
                    },
                    {
                        "hashtag": "blog",
                        "tag": "blog",
                        "tweets": 662,
                        "exposure": 4129362,
                        "retweets": 121,
                        "images": 35.9516602,
                        "links": 96.9788513,
                        "mentions": 10.7250757,
                        "color": 3,
                        "frequency": 0.717
                    },
                    {
                        "hashtag": "wordpress",
                        "tag": "wordpress",
                        "tweets": 442,
                        "exposure": 1271008,
                        "retweets": 87,
                        "images": 63.1221733,
                        "links": 99.0950241,
                        "mentions": 6.5610862,
                        "color": 3,
                        "frequency": 0.478
                    },
                    {
                        "hashtag": "web",
                        "tag": "web",
                        "tweets": 271,
                        "exposure": 485904,
                        "retweets": 67,
                        "images": 52.3985252,
                        "links": 98.5239868,
                        "mentions": 4.4280443,
                        "color": 3,
                        "frequency": 0.43
                    },
                    {
                        "hashtag": "digitalmarketing",
                        "tag": "digitalmarketing",
                        "tweets": 346,
                        "exposure": 2246708,
                        "retweets": 375,
                        "images": 27.7456646,
                        "links": 84.3930664,
                        "mentions": 14.4508667,
                        "color": 3,
                        "frequency": 0.43
                    },
                    {
                        "hashtag": "webdesign",
                        "tag": "webdesign",
                        "tweets": 188,
                        "exposure": 2333346,
                        "retweets": 45,
                        "images": 32.9787216,
                        "links": 95.2127686,
                        "mentions": 13.2978725,
                        "color": 3,
                        "frequency": 0.382
                    },
                    {
                        "hashtag": "socialmedia",
                        "tag": "socialmedia",
                        "tweets": 929,
                        "exposure": 11278025,
                        "retweets": 571,
                        "images": 26.4800854,
                        "links": 88.3745956,
                        "mentions": 23.3584499,
                        "color": 3,
                        "frequency": 0.382
                    }
                ]
            }


### Hashtag Stats [GET /v1/stats/multiple-hashtags{?tags}]

Returns real-time stats for up to 100 hashtags (updated hourly).

+ Parameters

    + tags (array, `jobs,hello`) ... Hashtag(s) without # mark

+ Request (text/html; charset=utf-8)

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "result": true,
                "code": 200,
                "hashtags": [
                    "jobs",
                    "hello"
                ],
                "message": "OK",
                "stats": [
                    {
                        "hashtag": "jobs",
                        "tag": "jobs",
                        "tweets": 2192,
                        "exposure": 6251488,
                        "retweets": 179,
                        "images": 0.032390511000000004,
                        "links": 0.994069366,
                        "mentions": 0.028284671,
                        "color": 3
                    },
                    {
                        "hashtag": "hello",
                        "tag": "hello",
                        "tweets": 46,
                        "exposure": 33075,
                        "retweets": 100,
                        "images": 0.369565201,
                        "links": 0.717391281,
                        "mentions": 0.08695652000000001,
                        "color": 2
                    }
                ],
                "color": [
                    "Unused",
                    "Overused",
                    "Good",
                    "Great"
                ]
            }


### Hashtag History [GET /v1/stats/history/{hashtag}]

Returns historical stats for a given hashtag from the last 30 days

+ Parameters

    + hashtag (string, `job`) ... Hashtag without # mark

+ Request (text/html; charset=utf-8)

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "result": true,
                "code": 200,
                "message": "OK",
                "hashtag": "job",
                "data": [
                    {
                        "date": "2017-07-02",
                        "tweets": 122100,
                        "retweets": 2400,
                        "links": 1.0,
                        "images": 0.02,
                        "mentions": 0.0,
                        "color": 3,
                        "exposure": 91003500
                    },
                    {
                        "date": "2017-07-03",
                        "tweets": 154800,
                        "retweets": 2600,
                        "links": 1.0,
                        "images": 0.03,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 161241400
                    },
                    {
                        "date": "2017-07-04",
                        "tweets": 146200,
                        "retweets": 3600,
                        "links": 1.0,
                        "images": 0.03,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 126351800
                    },
                    {
                        "date": "2017-07-05",
                        "tweets": 155000,
                        "retweets": 4900,
                        "links": 0.99,
                        "images": 0.03,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 126678900
                    },
                    {
                        "date": "2017-07-06",
                        "tweets": 157400,
                        "retweets": 7000,
                        "links": 1.0,
                        "images": 0.03,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 115540500
                    },
                    {
                        "date": "2017-07-07",
                        "tweets": 163800,
                        "retweets": 3400,
                        "links": 1.0,
                        "images": 0.02,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 148924500
                    },
                    {
                        "date": "2017-07-08",
                        "tweets": 143300,
                        "retweets": 3300,
                        "links": 1.0,
                        "images": 0.03,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 119823700
                    },
                    {
                        "date": "2017-07-09",
                        "tweets": 130900,
                        "retweets": 3100,
                        "links": 1.0,
                        "images": 0.02,
                        "mentions": 0.0,
                        "color": 3,
                        "exposure": 133067200
                    },
                    {
                        "date": "2017-07-10",
                        "tweets": 140200,
                        "retweets": 5300,
                        "links": 1.0,
                        "images": 0.03,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 129101400
                    },
                    {
                        "date": "2017-07-11",
                        "tweets": 153500,
                        "retweets": 4900,
                        "links": 1.0,
                        "images": 0.04,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 132328100
                    },
                    {
                        "date": "2017-07-12",
                        "tweets": 154800,
                        "retweets": 4200,
                        "links": 1.0,
                        "images": 0.03,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 135728800
                    },
                    {
                        "date": "2017-07-13",
                        "tweets": 150100,
                        "retweets": 4200,
                        "links": 1.0,
                        "images": 0.02,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 117356400
                    },
                    {
                        "date": "2017-07-14",
                        "tweets": 149900,
                        "retweets": 3700,
                        "links": 1.0,
                        "images": 0.03,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 127917200
                    },
                    {
                        "date": "2017-07-15",
                        "tweets": 140000,
                        "retweets": 3300,
                        "links": 1.0,
                        "images": 0.02,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 123001600
                    },
                    {
                        "date": "2017-07-16",
                        "tweets": 140400,
                        "retweets": 3700,
                        "links": 1.0,
                        "images": 0.02,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 98735200
                    },
                    {
                        "date": "2017-07-17",
                        "tweets": 132900,
                        "retweets": 2900,
                        "links": 1.0,
                        "images": 0.04,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 178846200
                    },
                    {
                        "date": "2017-07-18",
                        "tweets": 144400,
                        "retweets": 4900,
                        "links": 1.0,
                        "images": 0.03,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 207485900
                    },
                    {
                        "date": "2017-07-19",
                        "tweets": 147700,
                        "retweets": 5400,
                        "links": 1.0,
                        "images": 0.03,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 144647600
                    },
                    {
                        "date": "2017-07-20",
                        "tweets": 153700,
                        "retweets": 4000,
                        "links": 1.0,
                        "images": 0.02,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 146297300
                    },
                    {
                        "date": "2017-07-21",
                        "tweets": 159300,
                        "retweets": 4700,
                        "links": 1.0,
                        "images": 0.03,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 151610900
                    },
                    {
                        "date": "2017-07-22",
                        "tweets": 142100,
                        "retweets": 3200,
                        "links": 1.0,
                        "images": 0.01,
                        "mentions": 0.0,
                        "color": 3,
                        "exposure": 201673600
                    },
                    {
                        "date": "2017-07-23",
                        "tweets": 137500,
                        "retweets": 3900,
                        "links": 1.0,
                        "images": 0.01,
                        "mentions": 0.0,
                        "color": 3,
                        "exposure": 124774800
                    },
                    {
                        "date": "2017-07-24",
                        "tweets": 137500,
                        "retweets": 4600,
                        "links": 1.0,
                        "images": 0.03,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 138430200
                    },
                    {
                        "date": "2017-07-25",
                        "tweets": 150800,
                        "retweets": 4200,
                        "links": 1.0,
                        "images": 0.02,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 151774000
                    },
                    {
                        "date": "2017-07-26",
                        "tweets": 147100,
                        "retweets": 3800,
                        "links": 1.0,
                        "images": 0.02,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 127296100
                    },
                    {
                        "date": "2017-07-27",
                        "tweets": 149300,
                        "retweets": 5500,
                        "links": 1.0,
                        "images": 0.02,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 133474400
                    },
                    {
                        "date": "2017-07-28",
                        "tweets": 151000,
                        "retweets": 4400,
                        "links": 1.0,
                        "images": 0.02,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 143891400
                    },
                    {
                        "date": "2017-07-29",
                        "tweets": 71800,
                        "retweets": 2700,
                        "links": 1.0,
                        "images": 0.03,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 46194500
                    },
                    {
                        "date": "2017-07-30",
                        "tweets": 128400,
                        "retweets": 2000,
                        "links": 1.0,
                        "images": 0.03,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 100722500
                    },
                    {
                        "date": "2017-07-31",
                        "tweets": 136700,
                        "retweets": 4700,
                        "links": 1.0,
                        "images": 0.03,
                        "mentions": 0.01,
                        "color": 3,
                        "exposure": 192526400
                    }
                ],
                "color": [
                    "Unused",
                    "Overused",
                    "Good",
                    "Great"
                ]
            }


### Trending Hashtags [GET /v1/search/trending{?green,latin}]

Returns list of hashtags currently trending on Twitter

+ Parameters

    + green = `1` (optional, boolean) ... Restrict results only to green hashtags. Hides overused (red) hashtags.
    + latin = `1` (optional, boolean) ... Restrict results only to hashtags with latin characters

+ Request (text/html; charset=utf-8)

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "result": true,
                "message": "OK",
                "code": 200,
                "tags": [
                    {
                        "tag": "rayito",
                        "tweets": 6758,
                        "retweets": 1359,
                        "exposure": 1631062,
                        "links": 0.06777,
                        "photos": 0.03759,
                        "mentions": 0.95132,
                        "color": 3
                    },
                    {
                        "tag": "caelitrendy",
                        "tweets": 5733,
                        "retweets": 450,
                        "exposure": 1829783,
                        "links": 0.0014,
                        "photos": 0.0014,
                        "mentions": 0.00366,
                        "color": 3
                    },
                    {
                        "tag": "isabellacastillo",
                        "tweets": 5492,
                        "retweets": 216,
                        "exposure": 1770112,
                        "links": 0.00218,
                        "photos": 0.00528,
                        "mentions": 0.00218,
                        "color": 3
                    },
                    {
                        "tag": "dannapaola",
                        "tweets": 5321,
                        "retweets": 437,
                        "exposure": 1517079,
                        "links": 0.00319,
                        "photos": 0.00075,
                        "mentions": 0.00226,
                        "color": 3
                    },
                    {
                        "tag": "losrules",
                        "tweets": 5312,
                        "retweets": 434,
                        "exposure": 1573025,
                        "links": 0.00395,
                        "photos": 0.00151,
                        "mentions": 0.00075,
                        "color": 3
                    },
                    {
                        "tag": "job",
                        "tweets": 5258,
                        "retweets": 188,
                        "exposure": 7774871,
                        "links": 0.99772,
                        "photos": 0.0348,
                        "mentions": 0.01103,
                        "color": 3
                    },
                    {
                        "tag": "durodedomar",
                        "tweets": 4992,
                        "retweets": 429,
                        "exposure": 1385283,
                        "links": 0.0016,
                        "photos": 0.0008,
                        "mentions": 0.0016,
                        "color": 3
                    },
                    {
                        "tag": "trecru",
                        "tweets": 4879,
                        "retweets": 9,
                        "exposure": 97225,
                        "links": 1.0,
                        "photos": 0.99918,
                        "mentions": 0.0,
                        "color": 3
                    },
                    {
                        "tag": "hadith",
                        "tweets": 4754,
                        "retweets": 54,
                        "exposure": 4558750,
                        "links": 0.0,
                        "photos": 0.0,
                        "mentions": 0.0,
                        "color": 3
                    },
                    {
                        "tag": "sofiareyes",
                        "tweets": 4625,
                        "retweets": 554,
                        "exposure": 1793150,
                        "links": 0.00368,
                        "photos": 0.00454,
                        "mentions": 0.00173,
                        "color": 3
                    },
                    {
                        "tag": "newprofilepic",
                        "tweets": 4617,
                        "retweets": 2012,
                        "exposure": 6187642,
                        "links": 0.0026,
                        "photos": 0.99718,
                        "mentions": 0.01906,
                        "color": 3
                    },
                    {
                        "tag": "llegastetu",
                        "tweets": 4412,
                        "retweets": 534,
                        "exposure": 1722192,
                        "links": 0.00385,
                        "photos": 0.00385,
                        "mentions": 0.00181,
                        "color": 3
                    },
                    {
                        "tag": "kcacolombia",
                        "tweets": 4292,
                        "retweets": 4875,
                        "exposure": 3473008,
                        "links": 0.33108,
                        "photos": 0.06407,
                        "mentions": 0.2281,
                        "color": 3
                    },
                    {
                        "tag": "army",
                        "tweets": 4288,
                        "retweets": 8950,
                        "exposure": 820775,
                        "links": 0.09422,
                        "photos": 0.08745,
                        "mentions": 0.14762,
                        "color": 3
                    },
                    {
                        "tag": "news",
                        "tweets": 4262,
                        "retweets": 1171,
                        "exposure": 27098858,
                        "links": 0.9404,
                        "photos": 0.16917,
                        "mentions": 0.0596,
                        "color": 3
                    },
                    {
                        "tag": "giveaway",
                        "tweets": 4138,
                        "retweets": 1870,
                        "exposure": 3763296,
                        "links": 0.98574,
                        "photos": 0.02827,
                        "mentions": 0.39077,
                        "color": 3
                    },
                    {
                        "tag": "quran",
                        "tweets": 3900,
                        "retweets": 192,
                        "exposure": 6513488,
                        "links": 0.05231,
                        "photos": 0.0,
                        "mentions": 0.00103,
                        "color": 3
                    },
                    {
                        "tag": "hiring",
                        "tweets": 3817,
                        "retweets": 125,
                        "exposure": 2650117,
                        "links": 1.0,
                        "photos": 0.00445,
                        "mentions": 0.0021,
                        "color": 3
                    },
                    {
                        "tag": "michaelronda",
                        "tweets": 3692,
                        "retweets": 762,
                        "exposure": 1489250,
                        "links": 0.00677,
                        "photos": 0.00569,
                        "mentions": 0.00325,
                        "color": 3
                    }
                ]
            }


## Emojis [/v1/emoji/]

### Emoji Suggestions [GET /v1/emoji/suggestions{?text}]

Returns list of emoji suggestions for a given text of the post

+ Parameters

    + text (string, `Why robots may soon steal all manufacturing jobs – but it’s not all bad news`) ... Text of the post

+ Request (text/html; charset=utf-8)

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "result": true,
                "code": 200,
                "message": "OK",
                "emojis": [
                    "🤖",
                    "🗞",
                    "❓"
                ]
            }


### Auto-Emojify [GET /v1/emoji/auto-emojify{?text}]

Returns text of the post with emoji added

+ Parameters

    + text (string, `Why robots may soon steal all manufacturing jobs – but it’s not all bad news`) ... Text of the post

+ Request (text/html; charset=utf-8)

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "result": true,
                "code": 200,
                "message": "OK",
                "text": "Why robots may soon steal all manufacturing jobs – but it’s not all bad news 🤖🗞❓"
            }


## Influencers [/v1/influencers/]

### Influencers for a Hashtag [GET /v1/influencers/hashtag/{hashtag}]

Returns list of Twitter influencers for a given hashtag

+ Parameters

    + hashtag (string, `SocialMedia`) ... Hashtag without # mark

+ Request (text/html; charset=utf-8)

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "result": true,
                "code": 200,
                "message": "OK",
                "hashtag": "SocialMedia",
                "influencers": [
                    {
                        "username": "ExploreWeb2dot0",
                        "photo": "https://pbs.twimg.com/profile_images/577832064130527233/dswb_ru9.png",
                        "followers": 8820
                    },
                    {
                        "username": "elainebeare",
                        "photo": "https://pbs.twimg.com/profile_images/575758047663947776/e_-Fjs_0.png",
                        "followers": 7257
                    },
                    {
                        "username": "postoff25",
                        "photo": "https://pbs.twimg.com/profile_images/786249994437292032/GzTZPfg4.jpg",
                        "followers": 4981
                    },
                    {
                        "username": "GaryKnox",
                        "photo": "https://pbs.twimg.com/profile_images/378800000729732456/5e3a3f1fffa77cd245d4c0eeaccb8a44.png",
                        "followers": 3318
                    },
                    {
                        "username": "robertoalire",
                        "photo": "https://pbs.twimg.com/profile_images/713840111046291456/Wt1_5w1N.jpg",
                        "followers": 2747
                    },
                    {
                        "username": "_SEO_Simple_",
                        "photo": "https://pbs.twimg.com/profile_images/793979651861475329/uvU5aJjk.jpg",
                        "followers": 752
                    },
                    {
                        "username": "doublemacc",
                        "photo": "https://pbs.twimg.com/profile_images/868434989175668737/5lPmTmAc.jpg",
                        "followers": 636
                    },
                    {
                        "username": "BloggerAu",
                        "photo": "https://pbs.twimg.com/profile_images/538969297859538945/PH_ogi5q.png",
                        "followers": 355
                    },
                    {
                        "username": "PRvonHarsdorf",
                        "photo": "https://pbs.twimg.com/profile_images/1124965553/M_PRvHarsdorf_Logo_RGB_frei_klein.jpg",
                        "followers": 330
                    },
                    {
                        "username": "YIE_RA",
                        "photo": "https://pbs.twimg.com/profile_images/378800000184644934/12b755ce0eabd5b222428da63347028c.jpeg",
                        "followers": 312
                    }
                ]
            }


## Images [/v1/images/]

### Text to Image [GET /v1/images/quote{?quote,author,fontSize,quoteFont,quoteFontColor,authorFont,authorFontColor,enableHighlight,highlightColor,bgType,backgroundColor,gradientColor1,gradientColor2,gradientType,brandLogo}]

Returns URL of an image created from text according to given style parameters

+ Parameters

    + quote (string, `If you love life, don't waste time, for time is what life is made up of`) ... Text of the quote
    + author (string, `Bruce Lee`) ... Name of the author/source
    + fontSize (integer, `60`) ... Font size for the quote (author font size is calculated automatically)
    + quoteFont (string, `Lora`) ... Font-family used for quote text
    + quoteFontColor (string, `#4f4f4f`) ... Font color of the quote text
    + authorFont (string, `Lato Black`) ... Font-family used for author name
    + authorFontColor (string, `#e5e5e5`) ... Font color of the author
    + enableHighlight (integer, `1`) ... Enable highlight on quote text
    + highlightColor (string, `#f0ea66`) ... Color used for highlight
    + bgType (string, `gradient`) ... Background type (gradient/solid)
    + backgroundColor (string, `#000000`) ... Background color for solid background type
    + gradientType (string, `linear`) ... Type of gradient background (linear/radial)
    + gradientColor1 (string, `#1ee691`) ... First color for gradient background type
    + gradientColor2 (string, `#1ddad6`) ... Second color for gradient background type
    + brandLogo (url, `https://cdn.ritekit.com/assets/img/common/made-with-ritekit-white.png`) ... URL of the brand logo

+ Request (text/html; charset=utf-8)

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "result": true,
                "url": "https://media.ritekit.com/media/images/bf2509a8-4419-46d0-b630-91488249c873.jpeg"
            }


### Company Logo [GET /v1/images/logo{?domain}]

Returns a company logo based on website domain.

+ Parameters

    + domain (string, `google.com`) ... URL of the company

+ Request (text/html; charset=utf-8)

+ Response 200 (image/png)



## Link shortening [/v1/links/]

### Shorten Link [GET /v1/link/short-link{?url,cta}]

Returns a shorten link with a given CTA.

+ Parameters

    + url (string, `https://ritekit.com`) ... URL
    + cta (integer, `1`) ... cta id

+ Request (text/html; charset=utf-8)

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "result": true,
                "url": "rite.ly/Xe4o",
                "original": "https://ritekit.com",
                "service": "rite.ly",
                "ctaId": "1",
                "limit": {
                    "remaining": 5000
                }
            }


### List of CTAs [GET /v1/link/cta]

Returns list of available CTA for current user. Requires each user to authenticate with RiteKit

+ Request (text/html; charset=utf-8)

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "result": true,
                "list": [
                    {
                        "id": "bit.ly",
                        "name": "Bit.ly",
                        "code": "Bit.ly",
                        "default": 0
                    },
                    {
                        "id": 1,
                        "name": "Default",
                        "code": "DFLT",
                        "default": 1
                    }
                ]
            }